// Auto-generated by tools/build-content.js — do not edit manually

import { Card } from "../types";

export const CARDS: Card[] = [
  {
    "id": "card-mojeljrnixmc",
    "packId": "pack-moj4p7bua8gs",
    "title": "Animal Crossing Island Visits",
    "caption": "Oh my god I loveeeee animal crossing. Nice water bottle.",
    "date": "2022-05-23",
    "rarity": "everyday",
    "image": "animalcrossing.jpg"
  },
  {
    "id": "card-mojeomi9eq13",
    "packId": "pack-moj4p7bua8gs",
    "title": "Your Award Ceremony",
    "caption": "When I realized I was dating the smartest girl ever.",
    "date": "2022-05-31",
    "rarity": "favorite",
    "image": "awardceremony.jpeg"
  },
  {
    "id": "card-mojerxjx67o1",
    "packId": "pack-moj4p7bua8gs",
    "title": "Jazz Club",
    "caption": "Where we technically met",
    "date": "2018-02-14",
    "rarity": "everyday",
    "image": "jazzclub.jpeg"
  },
  {
    "id": "card-mojezy3jc97m",
    "packId": "pack-moj4p7bua8gs",
    "title": "Your High School Graduation",
    "caption": "I was super proud of you",
    "date": "2022-06-01",
    "rarity": "everyday",
    "image": "yourHSgraduation.jpeg"
  },
  {
    "id": "card-mojf3e8m9w6z",
    "packId": "pack-moj4p7bua8gs",
    "title": "Westfeild Mall Trip",
    "caption": "I should've bought that cow outfit",
    "date": "2022-05-28",
    "rarity": "everyday",
    "image": "malltrip.jpeg"
  },
  {
    "id": "card-mojf509u4jri",
    "packId": "pack-moj4p7bua8gs",
    "title": "Us but LEGO",
    "caption": "Plus the weird bird head guy. I think I still have little you somewhere",
    "date": "2022-05-28",
    "rarity": "everyday",
    "image": "legoreps.jpeg"
  },
  {
    "id": "card-mojf7wbv3dbq",
    "packId": "pack-moj4p7bua8gs",
    "title": "LEGO Spaceship Building",
    "caption": "Built while watching Avatar and Stranger Things, and doing nothing else...",
    "date": "2022-05-26",
    "rarity": "favorite",
    "image": "buildinglego.jpeg"
  },
  {
    "id": "card-mojfar323z9a",
    "packId": "pack-moj4p7bua8gs",
    "title": "First Date",
    "caption": "Salsas and a lemon in the Giant parking lot",
    "date": "2022-05-13",
    "rarity": "epic",
    "image": "firstdate.jpeg"
  },
  {
    "id": "card-mojfdvsg5o5d",
    "packId": "pack-moj4p7bua8gs",
    "title": "After Prom",
    "caption": "Aparently, I was supposed to kiss you here. Oops",
    "date": "2022-05-07",
    "rarity": "favorite",
    "image": "promafter.jpeg"
  },
  {
    "id": "card-mojff2xoj7ev",
    "packId": "pack-moj4p7bua8gs",
    "title": "W's only",
    "caption": "No caption needed",
    "date": "2022-04-27",
    "rarity": "legendary",
    "image": "wsonly.jpeg"
  },
  {
    "id": "card-mojfhyxvsvro",
    "packId": "pack-moj4p7bua8gs",
    "title": "First Prom",
    "caption": "my happy place",
    "date": "2022-05-07",
    "rarity": "milestone",
    "image": "myhappyplace1.jpeg"
  }
];
