// Auto-generated by tools/build-content.js — do not edit manually

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const CARD_IMAGES: Record<string, any> = {
  "animalcrossing.jpg": require("../assets/card-images/animalcrossing.jpg"),
  "awardceremony.jpeg": require("../assets/card-images/awardceremony.jpeg"),
  "jazzclub.jpeg": require("../assets/card-images/jazzclub.jpeg"),
  "yourHSgraduation.jpeg": require("../assets/card-images/yourHSgraduation.jpeg"),
  "malltrip.jpeg": require("../assets/card-images/malltrip.jpeg"),
  "legoreps.jpeg": require("../assets/card-images/legoreps.jpeg"),
  "buildinglego.jpeg": require("../assets/card-images/buildinglego.jpeg"),
  "firstdate.jpeg": require("../assets/card-images/firstdate.jpeg"),
  "promafter.jpeg": require("../assets/card-images/promafter.jpeg"),
  "wsonly.jpeg": require("../assets/card-images/wsonly.jpeg"),
  "myhappyplace1.jpeg": require("../assets/card-images/myhappyplace1.jpeg"),
};
