// Auto-generated by tools/build-content.js — do not edit manually

import { Pack } from "../types";

export const PACKS: Pack[] = [
  {
    "id": "pack-momjf66nf3cw",
    "name": "High School",
    "emoji": "🐈‍⬛",
    "description": "Tennis, Fast Food, and Driving Me Around",
    "coverColor": "#247203",
    "sortOrder": 0
  },
  {
    "id": "pack-momjjqv0n82v",
    "name": "Freshman Year",
    "emoji": "🚌",
    "description": "Pitt, Facetime, and Plants",
    "coverColor": "#0d3eaf",
    "sortOrder": 1
  }
];
