// Auto-generated by tools/build-content.js — do not edit manually

import { Pack } from "../types";

export const PACKS: Pack[] = [
  {
    "id": "pack-moj4p7bua8gs",
    "name": "High School Sweethearts",
    "emoji": "🎓",
    "description": "cougar hunt",
    "coverColor": "#0e7a00",
    "sortOrder": 0
  }
];
