#!/usr/bin/env node

// ==========================================
// Build Content Script
//
// Reads:   content/packs.json, content/cards.json, content/images/
// Writes:  data/packs.ts, data/cards.ts
// Copies:  content/images/* → assets/card-images/*
//
// Usage:   node tools/build-content.js
// ==========================================

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content");
const IMAGES_SRC = path.join(CONTENT_DIR, "images");
const IMAGES_DEST = path.join(ROOT, "assets", "card-images");
const DATA_DIR = path.join(ROOT, "data");

// --- Read JSON files ---

function readJSON(filename) {
  const filepath = path.join(CONTENT_DIR, filename);
  if (!fs.existsSync(filepath)) {
    console.error(`❌ Missing file: ${filepath}`);
    console.error(`   Export from the card creator tool first.`);
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(filepath, "utf-8"));
}

// --- Validate data ---

function validate(packs, cards) {
  const errors = [];
  const packIds = new Set(packs.map((p) => p.id));

  // Check cards reference valid packs
  cards.forEach((card) => {
    if (!packIds.has(card.packId)) {
      errors.push(`Card "${card.title}" references unknown pack: ${card.packId}`);
    }
  });

  // Check for missing images
  const missingImages = [];
  cards.forEach((card) => {
    if (!card.image) {
      errors.push(`Card "${card.title}" has no image filename`);
    } else if (fs.existsSync(IMAGES_SRC)) {
      const imgPath = path.join(IMAGES_SRC, card.image);
      if (!fs.existsSync(imgPath)) {
        missingImages.push(card.image);
      }
    }
  });

  if (missingImages.length > 0) {
    console.warn(`⚠️  ${missingImages.length} image(s) not found under content/images/:`);
    missingImages.forEach((img) => console.warn(`   - content/images/${img}`));
  }

  if (errors.length > 0) {
    console.error("❌ Validation errors:");
    errors.forEach((e) => console.error(`   - ${e}`));
    process.exit(1);
  }
}

// --- Generate TypeScript files ---

function generatePacksTS(packs) {
  const lines = [
    "// Auto-generated by tools/build-content.js — do not edit manually",
    "",
    'import { Pack } from "../types";',
    "",
    "export const PACKS: Pack[] = " + JSON.stringify(packs, null, 2) + ";",
    "",
  ];
  return lines.join("\n");
}

function generateCardsTS(cards) {
  const lines = [
    "// Auto-generated by tools/build-content.js — do not edit manually",
    "",
    'import { Card } from "../types";',
    "",
    "export const CARDS: Card[] = " + JSON.stringify(cards, null, 2) + ";",
    "",
  ];
  return lines.join("\n");
}

function generateImagesTS(cards) {
  const filenames = [...new Set(cards.map((c) => c.image).filter(Boolean))];
  const entries = filenames
    .map((f) => `  ${JSON.stringify(f)}: require("../assets/card-images/${f}"),`)
    .join("\n");
  return [
    "// Auto-generated by tools/build-content.js — do not edit manually",
    "",
    "// eslint-disable-next-line @typescript-eslint/no-explicit-any",
    "export const CARD_IMAGES: Record<string, any> = {",
    entries,
    "};",
    "",
  ].join("\n");
}

// --- Copy images ---

function copyImages(cards) {
  // Create destination directory
  if (!fs.existsSync(IMAGES_DEST)) {
    fs.mkdirSync(IMAGES_DEST, { recursive: true });
  }

  if (!fs.existsSync(IMAGES_SRC)) {
    console.warn("⚠️  No content/images/ directory found. Skipping image copy.");
    return 0;
  }

  let copied = 0;
  const imageFiles = new Set(cards.map((c) => c.image).filter(Boolean));

  imageFiles.forEach((filename) => {
    const src = path.join(IMAGES_SRC, filename);
    const dest = path.join(IMAGES_DEST, filename);

    if (fs.existsSync(src)) {
      // Create subdirectory if the image path contains a folder (e.g. packname/photo.jpg)
      const destDir = path.dirname(dest);
      if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
      fs.copyFileSync(src, dest);
      copied++;
    }
  });

  return copied;
}

// --- Main ---

function main() {
  console.log("📦 Building Memormon content...\n");

  // Read
  const packs = readJSON("packs.json");
  const cards = readJSON("cards.json");
  console.log(`   Found ${packs.length} packs and ${cards.length} cards`);

  // Validate
  validate(packs, cards);

  // Generate TypeScript
  fs.writeFileSync(path.join(DATA_DIR, "packs.ts"), generatePacksTS(packs));
  fs.writeFileSync(path.join(DATA_DIR, "cards.ts"), generateCardsTS(cards));
  console.log("   ✅ Generated data/packs.ts and data/cards.ts");

  // Copy images
  const imagesCopied = copyImages(cards);
  console.log(`   ✅ Copied ${imagesCopied} images to assets/card-images/`);

  // Generate image map
  fs.writeFileSync(path.join(DATA_DIR, "images.ts"), generateImagesTS(cards));
  console.log("   ✅ Generated data/images.ts");

  // Summary
  console.log("\n🎉 Done! Content is ready for the app.");

  // Rarity breakdown
  const rarityCount = {};
  cards.forEach((c) => {
    rarityCount[c.rarity] = (rarityCount[c.rarity] || 0) + 1;
  });
  console.log("\n   Rarity breakdown:");
  const symbols = { everyday: "♡", favorite: "♡♡", milestone: "★", epic: "★★", legendary: "👑" };
  Object.entries(rarityCount).forEach(([rarity, count]) => {
    const pct = ((count / cards.length) * 100).toFixed(1);
    console.log(`     ${symbols[rarity] || rarity} ${rarity}: ${count} (${pct}%)`);
  });
}

main();
